const HeroTypes = {
    SET_HERO_TYPE: 'SET_HERO_TYPE',
    SET_HERO_INDEX: 'SET_HERO_INDEX',
    SET_HERO_CNT: 'SET_HERO_CNT',
    SET_ALL_HERO: 'SET_ALL_HERO',
    GENERATE_HERO: 'GENERATE_HERO',
    GENERATE_HERO_PENDING: 'GENERATE_HERO_PENDING',
    GENERATE_HERO_FULFILLED: 'GENERATE_HERO_FULFILLED',
    GENERATE_ALL_HERO: 'GENERATE_ALL_HERO',
    GENERATE_ALL_HERO_PENDING: 'GENERATE_ALL_HERO_PENDING',
    GENERATE_ALL_HERO_FULFILLED: 'GENERATE_ALL_HERO_FULFILLED'
};


export {
    HeroTypes
}