const HeroTypes = {
    SET_HERO_TYPE: 'SET_HERO_TYPE',
    SET_HERO_INDEX: 'SET_HERO_INDEX',
    GENERATE_HERO: 'GENERATE_HERO',
    GENERATE_HERO_PENDING: 'GENERATE_HERO_PENDING',
    GENERATE_HERO_FULFILLED: 'GENERATE_HERO_FULFILLED'
};


export {
    HeroTypes
}